version: 2.1

orbs:
  python: cjw296/python-ci@5.1

common: &common
  jobs:

    - python/pip-run-tests:
        matrix:
          parameters:
            image:
              - cimg/python:3.11
              - cimg/python:3.12

    - python/typing:
        name: typing
        packages: manipulate tests
        image: cimg/python:3.12

    - python/coverage:
        name: coverage
        requires:
          - python/pip-run-tests

    - python/pip-setuptools-build-package:
        name: package
        requires:
          - typing
          - coverage

    - python/check-package:
        name: check-package
        package: manipulate
        typed: true
        requires:
          - package

    - python/release:
        name: release
        config: .carthorse.yml
        requires:
          - check-package
        filters:
          branches:
            only: master

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
